version: '3.7'
services:
  debezium:
    build:
      context: .
      dockerfile: ./docker/debezium/Dockerfile
    image: debezium
    depends_on:
      - postgres-debezium
    env_file:
      - .env
    # volumes:
    #   - my-mlflow-volume:/${MLFLOW_ARTIFACT_STORE}:z


  postgres-debezium:
    env_file:
      - .env
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    image: postgres-debezium
    restart: always
    ports:
      - 5432:5432
    # volumes:
    #   - pg-debezium:/var/lib/postgresql/data:z
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

# volumes:
#   pg-debezium:
#     external: false
